plugins:
  piratenlogin_enabled:
    default: false
  piratenlogin_discovery_document:
    default: ""
  piratenlogin_client_id:
    default: ""
  piratenlogin_client_secret:
    default: ""
  piratenlogin_authorize_scope:
    default: "openid"
  piratenlogin_verbose_logging:
    default: false
  piratenlogin_token_scope:
    default: ""
  piratenlogin_error_redirects:
    default: ''
    type: list
    list_type: secret
  piratenlogin_authorize_parameters:
    default: ''
    type: list
    list_type: compact
