plugins:
  piratenlogin_enabled:
    default: false
  piratenlogin_discovery_document:
    default: ""
  piratenlogin_client_id:
    default: ""
  piratenlogin_client_secret:
    default: ""
  piratenlogin_authorize_scope:
    default: "openid"
  piratenlogin_verbose_logging:
    default: false
  piratenlogin_token_scope:
    default: ""
  piratenlogin_error_redirects:
    default: ''
    type: list
    list_type: secret
  piratenlogin_authorize_parameters:
    default: ''
    type: list
    list_type: compact
  piratenlogin_group_sync_enabled:
    default: false
  piratenlogin_groups_claim:
    default: "groups"
  piratenlogin_group_parent_path:
    default: "/Worldwide"
  piratenlogin_group_mapping:
    default: |-
      BW|Baden-Wuerttemberg
      BY|Bayern
      BE|Berlin
      BB|Brandenburg
      HB|Bremen
      HH|Hamburg
      HE|Hessen
      MV|Mecklenburg
      NI|Niedersachsen
      NW|Nordrhein-Westfalen
      RP|Rheinland-Pfalz
      SL|Saarland
      SN|Sachsen
      ST|Sachsen-Anhalt
      SH|Schleswig-Holstein
      TH|Thueringen
    type: string
    textarea: true
